id: PCF0406E9
initial_creation_type: ocr
source_metadata:
  volumes:
    b71fac47737849678cddc7010f6241bc:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: བགེགས་བསྐྲད་པའི་སྒྲུབ་པའི་ཐབས།
      total_pages: 1648
      volume_number: 40
